### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by moobuilds** [koladev32/django-auth-react-tutorial#2]
The code is well written as well as the blog, one thing u must ve missed on in user/viewsets.py instead of importing from rest_framework.filters import OrderingFilter it should be replaced with
from rest_framework import filters
cuz in UserViewSet u used      filter_backends = [filters.OrderingFilter]

**Comment by koladev32** [comment]
Hey Vulture. Thanks for this. I am correcting it ASAP.
